
# The full qualified URI where redis is hosted
redis: 'localhost:6379'

# API Tokens
tokens:
  slack: ""
  darksky: ""
  zipcode: ""
  aws:
    access: ""
    secret: ""

# A list of admins by userid
# Admins have access to special commands (see commands/debug.go for some of them)
admins:
  - "U02GYT2PN"
  - "U02H1FS1C"

# A human readable location name for jarvis. used in jarvis status.
# The full text will read "I am currently hosted on <location>".
location: "My Computer"

# A channel blacklist.
# Any commands sent on these channels will be ignored
blacklist:
  - G0123456N

# A channel whitelist.
# If this list has at least one element, any commands sent to any channel except those in the whitelist will be ignored
whitelist:
  - G083EQ05N
